apiVersion: v1
kind: Service
metadata:
  name: hello-demo-service
spec:
  selector:
    app: hello-demo
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-demo
spec:
  selector:
    matchLabels:
      app: hello-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-demo
    spec:
      containers:
      - name: demo
        image: deepforu47/dockerk8sdemo:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
